[build]
command = "npx prisma@6.10.1 generate --schema=./prisma/schema.prisma && npx next build"
publish = ".next"

[build.environment]
PRISMA_GENERATE_SKIP_AUTOINSTALL = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"
